### ISSUE TITLE
Code review to DU 2

### ISSUE THREAD

**Issue by OksanaMir** [KatkaPrec/PROJEKT-Vizitka#1]
Ahoj Katko,
skvělá práce!

## ✅ Co je super:
- Stylování je čisté, srozumitelné a dobře strukturované.
- Používáš `position: absolute` + `transform` pro přesné zarovnání prvku `.eliska` – naprosto správně!
---

### 1. Konzistence v zápisu
Tady se objevuje mezera navíc, např.:
```css
background-color:#b2bec3 ;
```
Lepší je držet konzistentní styl:
```css
background-color: #b2bec3;
```

### 2. Responsivnější layout
Pevná šířka `550px` může na menších zařízeních dělat neplechu. Doporučuji použit `max-width`:
```css
.box {
    max-width: 550px;
}
```

### 3. Nepotřebuješ `width: 100%`, když máš `display: block`
Pokud nastavíš `a` nebo jiný inline element jako `block`, automaticky zabere celou šířku rodiče. Takže:
```css
.tlacitko {
    display: block;
    /* width: 100%; ← není třeba */
}
```

### 4. Doporučený zápis `font-weight` u Google Fonts
Google doporučuje místo `bold` nebo `normal` používat konkrétní číselné hodnoty mezi `200` a `1000`.
> <weight>: Použij hodnoty od 200 do 1000

Například:
```css
h1 {
    font-weight: 700; /* lepší než "bold" */
}
```

### 5. Základní velikost písma na `body`
Místo nastavování `font-size` třeba jen u `p` je lepší dát základ rovnou na `body`. Výsledek je konzistentnější typografie:
```css
body {
    font-size: 18px;
}
```

### 6. Jednodušší mezery mezi odstavci
Místo dvou různých tříd s `margin-top` a `margin-bottom` zvaž obalit odstavce do jednoho kontejneru a ten stylovat:
```css
.div-s-odstavci {
    margin-block: 30px;
}
```

---
